config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root "questions#index"

  resources :episodes

  resources :questions

  # get 'questionresult_result/:question_id/:episode_id', to: 'questions#result', as: :question_result
  post 'grade/:question_id/:episode_id', to: 'questions#grade', as: :question_result_post

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/episode.rb
class Episode < ApplicationRecord
  has_many :questions
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :episode
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController
  before_action :set_episode, only: %i[ show edit update destroy ]

  # GET /episodes or /episodes.json
  def index
    @episodes = Episode.all
  end

  # GET /episodes/1 or /episodes/1.json
  def show
  end

  # GET /episodes/new
  def new
    @episode = Episode.new
  end

  # GET /episodes/1/edit
  def edit
  end

  # POST /episodes or /episodes.json
  def create
    @episode = Episode.new(episode_params)

    respond_to do |format|
      if @episode.save
        format.html { redirect_to episode_url(@episode), notice: "Episode was successfully created." }
        format.json { render :show, status: :created, location: @episode }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @episode.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /episodes/1 or /episodes/1.json
  def update
    respond_to do |format|
      if @episode.update(episode_params)
        format.html { redirect_to episode_url(@episode), notice: "Episode was successfully updated." }
        format.json { render :show, status: :ok, location: @episode }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @episode.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /episodes/1 or /episodes/1.json
  def destroy
    @episode.destroy

    respond_to do |format|
      format.html { redirect_to episodes_url, notice: "Episode was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_episode
      @episode = Episode.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def episode_params
      params.require(:episode).permit(:season, :episode, :title)
    end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: %i[ show edit update destroy ]

  # GET /questions or /questions.json
  def index
    @season = params[:season] || '1'
    @question = Question.find(1)
    @episodes = Episode.where(season: @season).order(:episode)
  end

  # GET /questions/1 or /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # def result
  #   @question = Question.find(params[:question_id])
  #   @episode = Episode.find(params[:episode_id])

  #   @question.inspect

  #   @result = @question.episode == @episode
  # end

  # POST /questions/${question_id}/${episode_id}/grade
  def grade
    @question = Question.find(params[:question_id])
    @episode = Episode.find(params[:episode_id])

    @result = @question.episode == @episode

    redirect_to :root, notice: "You got it!" if @result
    redirect_to :root, notice: "Yikes. Embarrassing. Wrong." if !@result
  end


  # POST /questions or /questions.json
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to question_url(@question), notice: "Question was successfully created." }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1 or /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to question_url(@question), notice: "Question was successfully updated." }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1 or /questions/1.json
  def destroy
    @question.destroy

    respond_to do |format|
      format.html { redirect_to questions_url, notice: "Question was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def question_params
      params.require(:question).permit(:one, :two, :three, :episode_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/episodes_helper.rb
module EpisodesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/episodes/_episode.html.erb
<div id="<%= dom_id episode %>" class="flex border border-black rounded w-max">
  <p class="m-2">
    <%= episode.episode %>
  </p>

  <p class="m-2 font-bold">
    <%= episode.title %>
  </p>

</div>

app/views/episodes/_form.html.erb
<%= form_with(model: episode) do |form| %>
  <% if episode.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(episode.errors.count, "error") %> prohibited this episode from being saved:</h2>

      <ul>
        <% episode.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :season, style: "display: block" %>
    <%= form.number_field :season %>
  </div>

  <div>
    <%= form.label :episode, style: "display: block" %>
    <%= form.number_field :episode, step: '0.1', min: 1.0 %>
  </div>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/episodes/_seasons.html.erb
<div id="episodes" class="my-4 grid grid-cols-3 gap-2">




  <div>
    <%= form_tag(:root, method: :get) do %>
      <% (1..4).each do |s| %>
        <%= button_tag "Season #{s}", type: 'submit', name: 'season', value: "#{s}", class: "#{s == @season.to_i ? ' my-1 border p-2 bg-indigo-100 hover:bg-indigo-200' : 'my-1 border p-2 hover:bg-gray-100' }" %>
      <% end %>
    <% end %>
  </div>

  <div id="episodes" class="col-span-2">
    <% @episodes.each do |episode| %>
    <%= button_to episode.title, question_result_post_path(@question.id, episode.id), class: 'block hover:bg-gray-100 p-2 my-1 rounded border border-black' %>
    <% end %>
  </div>
</div>

app/views/episodes/edit.html.erb
<h1>Editing episode</h1>

<%= render "form", episode: @episode %>

<br>

<div>
  <%= link_to "Show this episode", @episode %> |
  <%= link_to "Back to episodes", episodes_path %>
</div>

app/views/episodes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Episodes</h1>

<div id="episodes">
  <% @episodes.each do |episode| %>
    <%= render episode %>
    <p>
      <%= link_to "Show this episode", episode %>
    </p>
  <% end %>
</div>

<%= link_to "New episode", new_episode_path %>

app/views/episodes/new.html.erb
<h1>New episode</h1>

<%= render "form", episode: @episode %>

<br>

<div>
  <%= link_to "Back to episodes", episodes_path %>
</div>

app/views/episodes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @episode %>

<div>
  <%= link_to "Edit this episode", edit_episode_path(@episode) %> |
  <%= link_to "Back to episodes", episodes_path %>

  <%= button_to "Destroy this episode", @episode, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SbQuotely</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28">
      <%= yield %>
    </main>
  </body>
</html>

app/views/questions/_form.html.erb
<%= form_with(model: question) do |form| %>
  <% if question.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
        <% question.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :one, style: "display: block" %>
    <%= form.text_field :one %>
  </div>

  <div>
    <%= form.label :two, style: "display: block" %>
    <%= form.text_field :two %>
  </div>

  <div>
    <%= form.label :three, style: "display: block" %>
    <%= form.text_field :three %>
  </div>

  <div>
    <%= form.label :episode_id, style: "display: block" %>
    <%= form.text_field :episode_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/questions/_question.html.erb
<div id="<%= dom_id question %>" class="my-4">
  <p class="my-4">
    <%= question.one %>
  </p>

  <p class="my-4">
    <%= question.two %>
  </p>

  <p class="my-4">
    <%= question.three %>
  </p>

</div>

app/views/questions/_question_dynamic.html.erb
<div id="<%= dom_id question %>" class="my-4">
  <p>
    <strong>One:</strong>
    <%= question.one %>
  </p>

  <p>
    <strong>Two:</strong>
    <%= question.two %>
  </p>

  <p>
    <strong>Three:</strong>
    <%= question.three %>
  </p>
</div>

app/views/questions/edit.html.erb
<h1>Editing question</h1>

<%= render "form", question: @question %>

<br>

<div>
  <%= link_to "Show this question", @question %> |
  <%= link_to "Back to questions", questions_path %>
</div>

app/views/questions/index.html.erb
<%- if notice %>
  <div class="bg-yellow-200 border border-black rounded p-8">
    <h3 class="text-xl text-center"><%= notice %></h3>
  </div>
<%- end %>


<h1 class="text-3xl font-bold my-6">SpongeBob Quotely</h1>

<div class="grid grid-cols-2 gap-8">
  <div id="question" class="border border-1 border-black rounded p-4">
    <h2 class="text-2xl font-bold">Quote</h2>
    <%= render @question %>
  </div>

  <div id="season-selector" class="border border-1 border-black rounded p-4">
  <h2 class="text-2xl font-bold">Episodes</h2>
    <%= render partial: 'episodes/seasons', locals: {episodes: @episodes, question: @question, season: @season} %>
  </div>


<%= link_to "New question", new_question_path, class: "text-blue-600" %>
<%= link_to "New episode", new_episode_path, class: "text-blue-600" %>

app/views/questions/new.html.erb
<h1>New question</h1>

<%= render "form", question: @question %>

<br>

<div>
  <%= link_to "Back to questions", questions_path %>
</div>

app/views/questions/result.html.erb
<% if @result %>
  <h1>You got it!</h1>
<% else %>
  <h1>Yikes. Embarrassing. Wrong.</h1>
<% end %>

app/views/questions/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @question %>

<div>
  <%= link_to "Edit this question", edit_question_path(@question) %> |
  <%= link_to "Back to questions", questions_path %>

  <%= button_to "Destroy this question", @question, method: :delete %>
</div>